services:
  - type: web
    name: nequi-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: nequi.settings.prod
      - key: RENDER_EXTERNAL_HOSTNAME
        value: ""   # Render llena RENDER_EXTERNAL_HOSTNAME autom√°ticamente en runtime
      - key: DATABASE_URL
        fromDatabase:
          name: nequi-db
          property: connectionString

databases:
  - name: nequi-db
    plan: free
